spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  data:
    elasticsearch:
      repositories:
        enabled:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 5
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    open-in-view: false
    properties:
      hibernate:
        # show-sql: true
        # format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: "/h2-console"
logging:
  level:
    root: info
    org:
      springframework: debug
      hibernate:
        SQL: debug
springdoc:
  packages-to-scan: me.kbh.elktoy
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  override-with-generic-response: false
  swagger-ui:
    path: demo-ui.html            # Swagger UI 경로 => localhost:8000/demo-ui.html
    tags-sorter: alpha            # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    operations-sorter: alpha      # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true
